/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mihua_frameproject_ndk_NdkDemo */

#ifndef _Included_com_mihua_frameproject_ndk_NdkDemo
#define _Included_com_mihua_frameproject_ndk_NdkDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mihua_frameproject_ndk_NdkDemo
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mihua_frameproject_ndk_NdkDemo_getStringFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
